name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libltdl-dev aidl
          pip install --upgrade pip
          pip install buildozer cython==0.29.33
      - name: Accept licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
          echo "24333f8a63b6825ea9c5514f83c1059b8ea731e8bbf8e9b3ea4c0eafb9d2a" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview2-license || true
      - name: Build
        run: buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: bin/*.apk
